[sop]

[sop.t]
action = "createnode"
param = "xform"
pre = ""
post = ""

[sop.w]
action = "createnode"
param = "attribwrangle"
pre = ""
post = ""

[sop.b]
action = "createnode"
param = "blast"

[sop.m]
action = "createnode"
param = "merge"

[sop.n]
action = "createnode"
param = "null"

[sop.g]
action = "createnode"
param = "groupcreate"

[sop.d]
action = "testing"

[vop]

[vop.b]
action = "createnode"
param = "bind"

[lop]

[lop.t]
action = "createnode"
param = "xform"

[obj]

[obj.g]
action = "createnode"
param = "geo"